modLoader = "javafml"
loaderVersion = "[41,)"
license = "MPL-2.0"
issueTrackerURL = "https://github.com/Silverminer007/Shrines/issues"

[[mods]]
modId = "shrines"
version = "${file.jarVersion}"
displayName = "Shrines"
updateJSONURL = "https://raw.githubusercontent.com/Silverminer007/MinecraftModsUpdateChecker/master/shrines-structures.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/shrines-structures"
credits = "https://github.com/Silverminer007/MinecraftModsUpdateChecker/blob/master/Credits-Shrines.md"
authors = "Silverminer007 and S1lencegamer"
description = '''
Shrines Structures is a World generation modication for Minecraft Java Edition focused on Structures
Also allows users to easily add own structures to world generation

See https://www.curseforge.com/minecraft/mc-mods/shrines-structures for more Info
'''

[[dependencies.shrines]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"