modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"
issueTrackerURL="https://github.com/Silverminer007/Shrines/issues" #optional
[[mods]] #mandatory
modId="shrines" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Shrines" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://github.com/Silverminer007/Shrines/raw/master/updateJSON.json" #optional
displayURL="https://github.com/Silverminer007/Shrines" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="Silverminer007" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.shrines]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[34,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.shrines]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"